catalog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),    
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'), # pk is expected by generic views
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'), # pk is expected by generic views
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'^librarian/$', views.LoanedBooksListView.as_view(), name='librarian-books'),
    url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
]

locallibrary/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    # Redirect base url to /catalog:
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
    url(r'^accounts/', include('django.contrib.auth.urls')), # Map some standard views as login/password & password reset stuff
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)

catalog/models.py
""" Models """
import uuid
from django.db import models
from django.urls import  reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    """ Book genre """
    name = models.CharField(max_length=200, help_text="Enter book genre")

    def __str__(self):
        return self.name


class Book(models.Model):
    """ Book representation """
    title = models.CharField(max_length=200)
    
    # Relation
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text="Enter brief description of the book")
    
    isbn = models.CharField('ISBN', max_length=13, help_text='13 character ISBN')
    
    # Relations
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    class Meta:
        ordering = ['title']

    def __str__(self):
        """ str() """
        return self.title

    def get_absolute_url(self):
        """ Returns detail view """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """ String rep of genres (max 3) """
        return ', '.join([genre.name for genre in self.genre.all()[:3] ])
    # As functions are objects themselfes I gues you can add properties to them...
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """ Model of book instances, ie. individual books that exist in the library """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this book")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1 , choices=LOAN_STATUS, blank=True, default='m', help_text="Book availability")

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back'] #NOTE some framework automagic rely on this one
        permissions = (('can_mark_returned', 'Set book as returned'),
                       ('can_edit', 'Edit book'))

    def __str__(self):
        """ str() """
        return "{} ({})".format(self.id, self.book.title)

class Author(models.Model):
        """ Author model """
        first_name = models.CharField(max_length=100)
        last_name = models.CharField(max_length=100)
        date_of_birth = models.DateField(null=True, blank=True)
        date_of_death = models.DateField('Died', null=True, blank=True)

        def get_absolute_url(self):
            """ Return detail author view """
            return reverse('author-detail', args=[str(self.id)])

        def __str__(self):
            """ str() """
            return "{}, {}".format(self.last_name, self.first_name)

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime 

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text='Enter a date between now and 4 weeks')
    
    # Yes the framework creates clean_<field> methods for all fields
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal is past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
from django.shortcuts import render

from .models import Book, Author, BookInstance, Genre

#from django.contrib.auth.decorators import login_required
#@login_required
def index(request):
    """ home page of site """

    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()

    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count() # implicit all()

    # Visit counter using sessions
    # Use sessions to keep track of individual anonymous users (using cookies)
    # By default session data is stored on the DB (default cookie life is 2 weeks)
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={'num_books':num_books, 
                 'num_instance':num_instances, 
                 'num_instances_available':num_instances_available,
                 'num_authors':num_authors,
                 'num_visits':num_visits},)

from django.views import generic

class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    model = Author


#from django.contrib.auth.mixins import LoginRequiredMixin
#class BookListView(LoginRequiredMixin, generic.ListView):
#    pass
#    ...


class BookListView(generic.ListView):
    model = Book
    paginate_by = 1 #NOTE built in pagination
    
    #context_object_name = 'alternative_name'
    #queryset = Book.objects.filter(title__icontains='war')
    #template_name = 'books/alternative_list.html'

    # def get_queryset(self): ... return Book.objects.filter(...)
    # def get_context_data(self, **kwargs):  ... return context
            
class BookDetailView(generic.DetailView):
    model = Book


# def book_detail_view(request,pk):
#     try:
#         book_id=Book.objects.get(pk=pk)
#     except Book.DoesNotExist:
#         raise Http404("Book does not exist")

#     #book_id=get_object_or_404(Book, pk=pk)
    
#     return render(
#         request,
#         'catalog/book_detail.html',
#         context={'book':book_id,}
#     )

from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """ List loaned books by current user """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        print("QUERY")
        return BookInstance.objects.filter(borrower=self.request.user) \
                                   .filter(status__exact='o') \
                                   .order_by('due_back')


from django.contrib.auth.mixins import PermissionRequiredMixin

class LoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        print("QUERY")
        return BookInstance.objects.filter(status__exact='o') \
                                   .order_by('due_back')


from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import datetime
from .forms import RenewBookForm

from django.contrib.auth.decorators import permission_required
# apply permission(s)

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            return HttpResponseRedirect(reverse('librarian-books'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renew_date': proposed_renewal_date,})

    return render(
        request,
        'catalog/book_renew_librarian.html',
        {'form':form, 'bookinst':book_inst})

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ author.first_name }} {{author.last_name}}</h1>

  <p><strong>Dates:</strong> (dates)</p> <!-- author detail link not yet defined -->

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    <!-- NOTE bookinstance_set is created by the framework -->
    {% for book in author.book_set.all %}
    <hr>
    <h4><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.bookinstance_set.all.count }})</h4>
    <p>{{ book.summary }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>

    <!-- NOTE: it's also possible to use 'object_list' -->
    {% if author_list %}
    <ul>

      {% for a in author_list %}
      <li>
        <a href="{{ a.get_absolute_url }}">{{ a.last_name }} {{a.first_name}}</a> (dates)
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors registred.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <!-- NOTE remember that if not forloop.last pattern -->
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    <!-- NOTE bookinstance_set is created by the framework -->
    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
  {% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    <!-- NOTE: it's also possible to use 'object_list' -->
    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
        <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}